config/routes.rb
Rails.application.routes.draw do

  # index
  root 'home#index'

  # session sign in/out
  get '/users/login' => 'sessions#new'
  post '/session' => 'sessions#create'
  get '/users/signout' => 'sessions#destroy'

  # Instagram auth routes
  get '/oauth' => 'users#oauth'
  get '/callback' => 'users#oauth_callback'

  # Force email with signup
  match '/users/:id/complete_signup' => 'users#complete_signup', via: [:get, :patch], :as => :complete_signup

  # Instagram import
  get '/users/:id/import_recent' => 'users#import_recent'

  resources :users do
    resources :photos
    resources :maps
  end


end

app/models/map.rb
class Map < ActiveRecord::Base
  belongs_to :user
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :map
  has_many :photos

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
  
  helper_method(:current_user, :logged_in?)

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end

end

app/controllers/maps_controller.rb
class MapsController < ApplicationController

  def show

    @user = User.find(params[:user_id])
    @map = Map.find(params[:id])

  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController


  def index
    @user = User.find(params[:user_id])
    @photos = Photo.where(user_id: params[:user_id] )
    respond_to do |format|
      format.json { render json: @photos }
      format.html { render :index }
    end
  end

  def create

    photo = Photo.create(photo_params)

    respond_to do |format|
      format.json { render json: photo }
    end

  end

  def destroy
    photo = Photo.find(params[:id])
    photo.destroy

    respond_to do |format|
      format.json { render json: photo }
    end
  end

  private

    def photo_params
      accessible = [ :user_id, :image_url, :latitude, :longitude ]
      params.require(:photo).permit(accessible)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create

  end

  def destroy
    session[:user_id] = nil
    redirect_to("/")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # Instagram ouauth redirect
  def oauth
    redirect_to Instagram.authorize_url(:redirect_uri => "http://instamapapp.herokuapp.com/callback")
  end

  # Instagram oauth callback currently malfunctioning on Instagram's end
  def oauth_callback

    response = Instagram.get_access_token(params[:code], :redirect_uri => "http://instamapapp.herokuapp.com/callback")

    user = User.find_or_create_by(instagram_id: response.user.id.to_i) do |user| 
      user.name = response.user.full_name 
      user.profile_picture = response.user.profile_picture
      map = Map.create(user_id: user.id)
    end
    
    user.instagram_access_token = response.access_token

    user.save
    session[:user_id] = user.id

    if user.email
      redirect_to "/users/#{user.id}"
    else
      redirect_to "/users/#{user.id}/complete_signup"
    end
  end

  # Collect email address
  def complete_signup
    @user = User.find(params[:id])
 
    if request.patch? && params[:user]
      if @user.update(user_params)
        redirect_to "/"
      else
        @show_errors = true
      end
    end

  end

  def import_recent

    @user = User.find(params[:id])
    client = Instagram.client(:access_token => @user.instagram_access_token)
    @photos = []
    client.user_recent_media.each do |media_item|
      unless media_item.location == nil
        photo = {}
        photo[:user_id] = @user.id
        photo[:image_url] = media_item.images.thumbnail.url
        photo[:latitude] = media_item.location.latitude
        photo[:longitude] = media_item.location.longitude
        photo[:saved] = Photo.exists?(image_url: photo[:image_url])

        @photos << photo
      end
    end

    respond_to do |format|
      format.html { render :import_recent }
      format.json { render json: @photos }
    end
  end

  def show
    @user = User.find(params[:id])
    @map = @user.map
  end

  private

    def user_params
      accessible = [ :name, :email ]
      params.require(:user).permit(accessible)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Instamap</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
   <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA05TWwYl5omZGDmpJy1JeuJYGDz1w-9M8"
    type="text/javascript"></script>
</head>
<body>
  <div id="menubar">
    <div id="logo">
      InstaMap
    </div>
    <div id="nav">
      <% if logged_in? %>
        <ul>
          <li>
            <%= link_to "Your Map", "/users/#{current_user.id}/" %>
          </li>
          <li>
            <%= link_to "Manage Photos", "/users/#{current_user.id}/photos" %>
          </li>
          <li>
            <%= link_to "Import Photos", "/users/#{current_user.id}/import_recent" %>
          </li>
        </ul>
      <% end %>
    </div>
    <div id="signin">
      <% if logged_in? %>
        <div class="signin-text">
          <%= current_user.name %>
          <%= link_to "(Sign out)", "/users/signout" %>
        </div>
        <div id="user-image" style="background-image: url(<%= current_user.profile_picture %>); background-size: cover; height: 50px; width: 50px; float: right">
        </div>
      <% else %>
        <div class="signin-text">
          <%= link_to "Sign with Instagram", "/oauth" %>
        </div>
      <% end %>
    </div>  
  </div>

  <div id="wrapper">
    <%= yield %>
  </div>

</body>
</html>

app/views/photos/_edit_photo.html.erb
<div class="import-photo" style='float:left;'>
  <br/> 
  <img src='<%= "#{photo[:image_url]}" %>'>
  <%= form_for([@user, photo], remote: true) do |f| %>
    <%= hidden_field_tag "user_id", "#{photo.user_id}"  %>
    <%= hidden_field_tag "image_url", "#{photo.image_url}"  %>
    <%= hidden_field_tag "latitude", "#{photo.latitude}"  %>
    <%= hidden_field_tag "longitude", "#{photo.longitude}"  %>
    <%= f.submit("Remove from map", id: photo.id) %>
  <% end %>
</div>

app/views/photos/_import_photo.html.erb
<div class="import-photo" style='float:left;'>
  <br/> 
  <% if photo[:saved] == true %>
    <img src='<%= "#{photo[:image_url]}" %>'>
    <% saved_photo = Photo.find_by(image_url: photo[:image_url]) %>
    <%= form_for([@user, saved_photo], remote: true) do |f| %>
      <%= hidden_field_tag "user_id", "#{photo[:user_id]}"  %>
      <%= hidden_field_tag "image_url", "#{photo[:image_url]}"  %>
      <%= hidden_field_tag "latitude", "#{photo[:latitude]}"  %>
      <%= hidden_field_tag "longitude", "#{photo[:longitude]}"  %>
      <%= hidden_field_tag "saved", "#{photo[:saved]}"  %>
      <%= f.submit("Remove from map", id: saved_photo.id) %>
    <% end %>
  <% else %>
    <img src='<%= "#{photo[:image_url]}" %>'>
    <%= form_for([@user, Photo.new], remote: true) do |f| %>
      <%= hidden_field_tag "user_id", "#{photo[:user_id]}"  %>
      <%= hidden_field_tag "image_url", "#{photo[:image_url]}"  %>
      <%= hidden_field_tag "latitude", "#{photo[:latitude]}"  %>
      <%= hidden_field_tag "longitude", "#{photo[:longitude]}"  %>
      <%= hidden_field_tag "saved", "#{photo[:saved]}"  %>
      <%= f.submit("Add to map") %>
    <% end %>
  <% end %>
</div>

app/views/photos/index.html.erb
<div id="inner-wrapper">
  <h1>Your InstaMapped Photos</h1>

  <%= render partial: "/photos/edit_photo", collection: @photos, as: "photo" %>
</div>

app/views/users/complete_signup.html.erb
<div id="inner-wrapper">
  <%= form_for(@user, :as => 'user', :url => complete_signup_path(@user), :html => { role: 'form', style: 'padding-top: 50px'}) do |f| %>
      <%= f.text_field :email, :autofocus => true, :value => '', placeholder: 'Example: email@me.com' %>

      <p>Please confirm your email address.</p>

      <%= f.submit 'Submit', id: "email" %>
  <% end %>
</div>

app/views/users/import_recent.html.erb
<div id="inner-wrapper">
  <h1>Your recent media</h1>

  <%= render partial: "/photos/import_photo", collection: @photos, as: "photo" %>
</div>

app/views/users/login.html.erb
<h1>Sign In</h1>

<%= form_tag("/session", action: "create") do %>
  <p>
    <%= label_tag(:email) %>:
    <%= text_field_tag(:email) %>
  </p>
  <p>
    <%= label_tag(:password) %>:
    <%= password_field_tag(:password) %>
  </p>
  <p>
    <%= submit_tag("Login") %>
  </p>
<% end %>
<p>
  Don't have an account? <%= link_to "Create one!", new_user_path %>
</p>

app/views/users/new.html.erb
<h1>Create New User</h1>

<%= form_for User.new do |f| %>
  <p>
    <%= f.label(:name) %>:
    <%= f.text_field(:name) %>
  </p>
  <p>
    <%= f.label(:email) %>:
    <%= f.text_field(:email) %>
  </p>
  <p>
    <%= f.label(:password) %>:
    <%= f.password_field(:password) %>
  </p>
  <p>
    <%= f.label(:password_confirmation) %>:
    <%= f.password_field(:password_confirmation) %>
  </p>
  <p>
    <em>(Password must be between 8-16 characters.)</em>
  </p>
  <p>
    <%= f.submit("Create User") %>
  </p>
<% end %>

app/views/users/show.html.erb
<div id="inner-wrapper">

  <div id="map-container">
    <div id="map-canvas">
      InstaMap
    </div>
    <div id="target"></div>
  </div>
</div>

<script>
  function initialize() {

    $.ajax({
        url: "/users/" + <%= "#{@user.id}" %> + "/photos",
        type: "get"
     }).done(function(data) {
        console.log(data);
        onDataLoaded(data);
    });

    var mapOptions = {
      center: new google.maps.LatLng(40.7590615, -73.969231,12),
      zoom: 2
    };


  //Create map and add to "map-canvas" div
    var map = new google.maps.Map(document.getElementById("map-canvas"),
        mapOptions);


    // Runs when we get a response from the server
    onDataLoaded = function(photos) {  

      var photos = photos;

      // If the array of user's data isn't empty
      if(photos.length > 0) {

        // Iterate over the array of user's photos
        for (var i in photos ){
          
          // Create a pin with the photo
          var photo = photos[i]
            
          var image = {
            url: photos[i].image_url,
            size: new google.maps.Size(50, 50),
            origin: new google.maps.Point(0,0),
            anchor: new google.maps.Point(25, 25),
            scaledSize: new google.maps.Size(50, 50)
          };

          var myLatLng = new google.maps.LatLng(photo.latitude, photo.longitude);

          var customMarker = new google.maps.Marker({
              position: myLatLng,
              map: map,
              icon: image
          });

        }
      } else {
        // Display error if no photos in the array
        $('#target').append("<p>Hmm...I couldn't find anything to display! Try importing your photos from Instagram!</p>");
      }
    }
  }


  $(document).ready(initialize);
</script>